var dialog = new Window("dialog", "Place your LaTeX Equation");

// Crop checkbox
var cropCheckbox = dialog.add("checkbox", undefined, "Crop the result");
cropCheckbox.value = true;

// Input box, size
var latexInput = dialog.add("edittext", undefined, "", {multiline: true});
latexInput.size = [800, 600];

// Preamble and closure for LaTeX
var latexPreamble = "\\documentclass{article}\n\\pagestyle{empty}\n\\begin{document}\n";
var latexClosure = "\n\\end{document}";

latexInput.text = latexPreamble + latexClosure;

// Add OK and Cancel buttons
var buttonsGroup = dialog.add("group");
buttonsGroup.add("button", undefined, "OK", {name: "ok"});
buttonsGroup.add("button", undefined, "Cancel", {name: "cancel"});

// Show the dialog
if (dialog.show() != 1) {
    exit();
}

// Extract the LaTeX code from the input
var splits = latexInput.text.split("\\begin{document}");
var userLatex = "";
if (splits.length > 1) {
    var innerSplits = splits[1].split("\\end{document}");
    if (innerSplits.length > 0) {
        userLatex = innerSplits[0];
    }
    latexPreamble = splits[0] + "\\begin{document}\n";
    latexClosure = "\n\\end{document}" + (innerSplits.length > 1 ? innerSplits[1] : "");
}

var fullLatexCode = latexPreamble + userLatex + latexClosure;

var docDir = app.activeDocument.filePath;

// Name of the sub-directory for .tex files
var texSubDirName = "texFiles";
// Full path to the sub-directory
var texSubDir = new Folder(docDir + "/" + texSubDirName);
// If the sub-directory doesn't exist, create it
if (!texSubDir.exists) {
    texSubDir.create();
}

// Generate unique file name based on current timestamp
var now = new Date();
var year = now.getFullYear();
var month = ("0" + (now.getMonth() + 1)).slice(-2);
var day = ("0" + now.getDate()).slice(-2);
var hour = ("0" + now.getHours()).slice(-2);
var minute = ("0" + now.getMinutes()).slice(-2);
var second = ("0" + now.getSeconds()).slice(-2);

var formattedTime = year + "-" + month + "-" + day + "-" + hour + "-" + minute + "-" + second;
var latexFileName = "latexInput_" + formattedTime + ".tex";

var latexFile = new File(texSubDir + "/" + latexFileName);

latexFile.encoding = "UTF8";
latexFile.open('w');
latexFile.writeln(fullLatexCode);
latexFile.close();

// Compile
var batFile = new File(texSubDir + "/tempExecute.bat");
batFile.open('w');
batFile.writeln('@echo off');
batFile.writeln('cd /d "' + texSubDir.fsName + '"');
// Just call xelatex directly
batFile.writeln('xelatex -interaction=nonstopmode "' + latexFileName + '"');

// If crop is selected, run pdfcrop
if (cropCheckbox.value) {
    var pdfName = latexFileName.replace(".tex", ".pdf");
    batFile.writeln('if exist "' + pdfName + '" (');
    batFile.writeln('  mkdir tempDir 2>nul');
    batFile.writeln('  move "' + pdfName + '" "tempDir\\' + pdfName + '"');
    batFile.writeln('  pdfcrop "tempDir\\' + pdfName + '" "tempDir\\' + pdfName + '"');
    batFile.writeln('  move "tempDir\\' + pdfName + '" "' + pdfName + '"');
    batFile.writeln('  rmdir /s /q tempDir 2>nul');
    batFile.writeln(')');
}

batFile.close();

// Execute the batch file
batFile.execute();

// Wait for PDF generation
var maxAttempts = 30;
var attempt = 0;
var pdfGenerated = false;
var pdfPath = texSubDir + "/" + latexFileName.replace(".tex", ".pdf");
var pdfFile = new File(pdfPath);

while (attempt < maxAttempts && !pdfGenerated) {
    if (pdfFile.exists) {
        pdfGenerated = true;
    } else {
        $.sleep(1000);
        attempt++;
    }
}

batFile.remove();

// Clean up auxiliary files generated by LaTeX
function cleanupLatexFiles() {
    var extensions = [".aux", ".log", ".out", ".synctex.gz"];
    var baseName = latexFileName.replace(".tex", "");
    
    for (var i = 0; i < extensions.length; i++) {
        var auxFile = new File(texSubDir + "/" + baseName + extensions[i]);
        if (auxFile.exists) {
            try {
                auxFile.remove();
            } catch(e) {
                // Ignore if file can't be deleted
            }
        }
    }
}

// Clean up LaTeX auxiliary files
cleanupLatexFiles();

if (pdfGenerated) {
    app.activeDocument.place(pdfFile);
} else {
    alert("Error generating PDF.\n\n" +
          "Make sure:\n" +
          "1. xelatex is in your system PATH\n" +
          "2. Or try using pdflatex instead (just change 'xelatex' to 'pdflatex' in the script)");
}